### ISSUE TITLE
"github.com/advancedlogic/gojs-config" is no longer available 

### ISSUE THREAD

**Issue by truongsinh** [advancedlogic/GoOse#41]
https://github.com/advancedlogic/GoOse/blob/9df1c62bade124335ec97d0d845391ee54631b6f/configuration.go#L4

**Comment by truongsinh** [comment]
temporarily replaced with https://github.com/Smarp/gojs-config

**Comment by allochi** [comment]
Hi, I wish if this can be closed asap, I can't install GoOse because of it. Thanks!

**Comment by advancedlogic** [comment]
Because GoOse at the moment was not using a configuration file. For now I skip it. It's temporary.
Let me know if this works for you or you use an external configuration file.

**Comment by allochi** [comment]
Perfect! Thanks!

**Comment by advancedlogic** [comment]
There is configuration.go now
