### ISSUE TITLE
Wrong Content-Type in request

### ISSUE THREAD

**Issue by shaneiseminger** [advancedlogic/GoOse#67]
Current code sets a `Content-Type` header of `application/json` to request HTML. It should use `text/html`. 

This causes some URL requests to fail when servers pay attention to this header and don't have any way of serving JSON.

Opening a PR.

**Comment by advancedlogic** [comment]
Fixed

**Comment by shaneiseminger** [comment]
Thanks for this. Why use `text/plain` instead of `text/html`? I haven't tested it, but I would think `text/plain` could be subject to failures similar to those that can happen with `application/json`.
